name: Publish package candidate to Hackage

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: 'latest'
          cabal-version: 'latest'
      - run: |
          cabal v2-sdist --output-directory='${{ runner.temp }}/packages' all
      - uses: haskell-actions/hackage-publish@v1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          packagesPath: ${{ runner.temp }}/packages
          publish: false    
